DROP TABLE CHAT;
DROP SEQUENCE CHAT_SEQ

CREATE TABLE CHAT(
	CHATID NUMBER PRIMARY KEY,
	CHATNAME VARCHAR2(20),
	CHATCONTENT VARCHAR2(100),
	CHATTIME DATE
);

CREATE SEQUENCE CHAT_SEQ
start with 1
increment by 1
nocache

select * from chat; 